[h: 'This macro will update a token with a statblock from Archives of Nethys']
[h: ids = getSelected()]
[h: assert(json.length(ids) > 0, "Select at least one token.", 0)]

[h: status = input("spellID|1565|Enter URL|TEXT|WIDTH=60")]
[h: abort(status)]

[h: urlIndex = 'https://elasticsearch.aonprd.com/json-data/aon73-index.json']
[h: htmlIndex = REST.get(urlIndex, '{"Accept": ["text/html"], "Accept-Encoding": [""]}', 0)]

[h: targetSpell = "spell-" + spellID]
[h: indexKeyFound = ""]

[h: keys = json.fields(htmlIndex)]
[h: keyCount = listcount(keys)]

[h, for(i, 0, keyCount), code: {
	[h: key = listGet(keys, i)]
	[h: arr = json.get(htmlIndex, key)]
	[h: found = json.contains(arr, targetSpell)]
	[h, if(found == 1), code: {
		[h: indexKeyFound = key]
	}]
}]

[r: "Target: " + targetSpell + "<br>"]
[r: "Index Key: " + indexKeyFound + "<br />"]

[h: urlData = 'https://elasticsearch.aonprd.com/json-data/' + indexKeyFound + '.json']
[h: htmlData = REST.get(urlData, '{"Accept": ["text/html"], "Accept-Encoding": [""]}', 0)]

[h: spellData = ""]

[h: keyCount = json.length(htmlData)]
[h, for(i, 0, keyCount), code: {
	[h: spellID = ""]
	[h: obj = json.get(htmlData, i)]
	[h: objID = json.get(obj, "id")]
	[h, if(objID == targetSpell), code: {
		[h: spellData = obj]
	}]
}]

[h: spellData]

[h: spell_actions = json.get(spellData, "actions")]
[h: spell_bloodline_markdown = json.get(spellData, "bloodline_markdown")]
[h: spell_component = json.get(spellData, "component")]
[h: spell_domain_markdown = json.get(spellData, "domain_markdown")]
[h: spell_element = json.get(spellData, "element")]
[h: spell_heighten = json.get(spellData, "heighten")]
[h: spell_heighten_group = json.get(spellData, "heighten_group")]
[h: spell_heighten_level = json.get(spellData, "heighten_level")]
[h: spell_id = json.get(spellData, "id")]
[h: spell_legacy_id = json.get(spellData, "legacy_id")]
[h: spell_level = json.get(spellData, "level")]
[h: spell_markdown = json.get(spellData, "markdown")]
[h: spell_mystery_markdown = json.get(spellData, "mystery_markdown")]
[h: spell_name = json.get(spellData, "name")]
[h: spell_pfs = json.get(spellData, "pfs")]
[h: spell_primary_source_category = json.get(spellData, "primary_source_category")]
[h: spell_range = json.get(spellData, "range")]
[h: spell_range_raw = json.get(spellData, "range_raw")]
[h: spell_rarity = json.get(spellData, "rarity")]
[h: spell_rarity_id = json.get(spellData, "rarity_id")]
[h: spell_release_date = json.get(spellData, "release_date")]
[h: spell_remaster_id = json.get(spellData, "remaster_id")]
[h: spell_resistance = json.get(spellData, "resistance")]
[h: spell_saving_throw_markdown = json.get(spellData, "saving_throw_markdown")]
[h: spell_school = json.get(spellData, "school")]
[h: spell_search_markdown = json.get(spellData, "search_markdown")]
[h: spell_source = json.get(spellData, "source")]
[h: spell_source_category = json.get(spellData, "source_category")]
[h: spell_source_markdown = json.get(spellData, "source_markdown")]
[h: spell_speed = json.get(spellData, "speed")]
[h: spell_spell_type = json.get(spellData, "spell_type")]
[h: spell_summary_markdown = json.get(spellData, "summary_markdown")]
[h: spell_target_markdown = json.get(spellData, "target_markdown")]
[h: spell_tradition = json.get(spellData, "tradition")]
[h: spell_tradition_markdown = json.get(spellData, "tradition_markdown")]
[h: spell_trait = json.get(spellData, "trait")]
[h: spell_trait_markdown = json.get(spellData, "trait_markdown")]
[h: spell_type = json.get(spellData, "type")]
[h: spell_url = json.get(spellData, "url")]
[h: spell_weakness = json.get(spellData, "weakness")]

[r: 'spell_actions: ' + spell_actions + '<br />']
[r: 'spell_bloodline_markdown: ' + spell_bloodline_markdown + '<br />']
[r: 'spell_component: ' + spell_component + '<br />']
[r: 'spell_domain_markdown: ' + spell_domain_markdown + '<br />']
[r: 'spell_element: ' + spell_element + '<br />']
[r: 'spell_heighten: ' + spell_heighten + '<br />']
[r: 'spell_heighten_group: ' + spell_heighten_group + '<br />']
[r: 'spell_heighten_level: ' + spell_heighten_level + '<br />']
[r: 'spell_id: ' + spell_id + '<br />']
[r: 'spell_legacy_id: ' + spell_legacy_id + '<br />']
[r: 'spell_level: ' + spell_level + '<br />']
[r: 'spell_markdown: ' + spell_markdown + '<br />']
[r: 'spell_mystery_markdown: ' + spell_mystery_markdown + '<br />']
[r: 'spell_name: ' + spell_name + '<br />']
[r: 'spell_pfs: ' + spell_pfs + '<br />']
[r: 'spell_primary_source_category: ' + spell_primary_source_category + '<br />']
[r: 'spell_range: ' + spell_range + '<br />']
[r: 'spell_range_raw: ' + spell_range_raw + '<br />']
[r: 'spell_rarity: ' + spell_rarity + '<br />']
[r: 'spell_rarity_id: ' + spell_rarity_id + '<br />']
[r: 'spell_release_date: ' + spell_release_date + '<br />']
[r: 'spell_remaster_id: ' + spell_remaster_id + '<br />']
[r: 'spell_resistance: ' + spell_resistance + '<br />']
[r: 'spell_saving_throw_markdown: ' + spell_saving_throw_markdown + '<br />']
[r: 'spell_school: ' + spell_school + '<br />']
[r: 'spell_search_markdown: ' + spell_search_markdown + '<br />']
[r: 'spell_source: ' + spell_source + '<br />']
[r: 'spell_source_category: ' + spell_source_category + '<br />']
[r: 'spell_source_markdown: ' + spell_source_markdown + '<br />']
[r: 'spell_speed: ' + spell_speed + '<br />']
[r: 'spell_spell_type: ' + spell_spell_type + '<br />']
[r: 'spell_summary_markdown: ' + spell_summary_markdown + '<br />']
[r: 'spell_target_markdown: ' + spell_target_markdown + '<br />']
[r: 'spell_tradition: ' + spell_tradition + '<br />']
[r: 'spell_tradition_markdown: ' + spell_tradition_markdown + '<br />']
[r: 'spell_trait: ' + spell_trait + '<br />']
[r: 'spell_trait_markdown: ' + spell_trait_markdown + '<br />']
[r: 'spell_type: ' + spell_type + '<br />']
[r: 'spell_url: ' + spell_url + '<br />']
[r: 'spell_weakness: ' + spell_weakness + '<br />']