[h: args = macro.args]
[h: tokenID = args]
[h, if(args != "" && json.type(args) == "OBJECT" && json.contains(args, "tokenID")): tokenID = json.get(args, "tokenID")]

[h: assert(tokenID != "", "No token id passed to _AddRebuildAonMacro.", 0)]

[h: macroCommand = "[h: tokenID = currentToken()]"]
[h: macroCommand = macroCommand + decode("%0A") + "[h: creatureData = getProperty('AON_JSON_RAW')]"]
[h: macroCommand = macroCommand + decode("%0A") + "[h: assert(creatureData != '', 'AON_JSON_RAW is blank.', 0)]"]
[h: macroCommand = macroCommand + decode("%0A") + "[h: assert(json.type(creatureData) == 'OBJECT', 'AON_JSON_RAW is not a JSON object.', 0)]"]
[h: macroCommand = macroCommand + decode("%0A") + "[h: aonURL = getProperty('AON_URL')]"]
[h: macroCommand = macroCommand + decode("%0A") + "[h: aonImageURL = getProperty('AON_IMG_URL')]"]
[h: macroCommand = macroCommand + decode("%0A") + "[h: creatureID = getProperty('AON_SourceID')]"]
[h: macroCommand = macroCommand + decode("%0A") + "[h: aonCreatureNumber = getProperty('AON_ID')]"]
[h: macroCommand = macroCommand + decode("%0A") + "[h: aonType = getProperty('AON_Type')]"]
[h: macroCommand = macroCommand + decode("%0A") + "[h: propertyArgs = json.set('{}', 'tokenID', tokenID, 'creatureData', creatureData, 'aonURL', aonURL, 'aonImageURL', aonImageURL, 'creatureID', creatureID, 'aonCreatureNumber', aonCreatureNumber, 'aonType', aonType)]"]
[h: macroCommand = macroCommand + decode("%0A") + "[h, macro('_SetCreatureProperties@Lib:AON'): propertyArgs]"]
[h: macroCommand = macroCommand + decode("%0A") + "[g,r: 'AON properties rebuilt.']"]
[h: macroProps = json.set("{}", "label", "REBUILD_AON", "command", macroCommand, "autoExecute", 1, "playerEditable", 1, "group", "z_AON")]
[h: createMacro(macroProps, tokenID)]
