[h: args = macro.args]
[h: tokenID = args]
[h, if(args != "" && json.type(args) == "OBJECT" && json.contains(args, "tokenID")): tokenID = json.get(args, "tokenID")]

[h: assert(tokenID != "", "No token id passed to _AddParsedSpecialAbilities.", 0)]

[h: aonJson = getProperty("AON_JSON", tokenID)]
[h: assert(aonJson != "", "AON_JSON is blank.", 0)]
[h: assert(json.type(aonJson) == "OBJECT", "AON_JSON is not a JSON object.", 0)]
[h: assert(json.contains(aonJson, "Parsed"), "AON_JSON.Parsed is missing.", 0)]

[h: parsed = json.get(aonJson, "Parsed")]
[h: abilities = "[]"]
[h, if(json.contains(parsed, "Abilities")): abilities = json.get(parsed, "Abilities")]
[h: assert(json.type(abilities) == "ARRAY", "AON_JSON.Parsed.Abilities is not a JSON array.", 0)]

[h: abilityCount = json.length(abilities)]
[h, for(i, 0, abilityCount), code: {
	[h: abilityData = json.get(abilities, i)]
	[h: abilityName = "Ability"]
	[h, if(json.contains(abilityData, "Name")): abilityName = json.get(abilityData, "Name")]
	[h: macroGroup = "1. Special Abilities"]

	[h: featLevel = ""]
	[h, if(json.contains(abilityData, "FeatLevel")): featLevel = json.get(abilityData, "FeatLevel")]
	[h: traits = "[]"]
	[h, if(json.contains(abilityData, "Traits")): traits = json.get(abilityData, "Traits")]
	[h: trigger = ""]
	[h, if(json.contains(abilityData, "Trigger")): trigger = json.get(abilityData, "Trigger")]
	[h: requirements = ""]
	[h, if(json.contains(abilityData, "Requirements")): requirements = json.get(abilityData, "Requirements")]
	[h: action = ""]
	[h, if(json.contains(abilityData, "Action")): action = json.get(abilityData, "Action")]
	[h: text = ""]
	[h, if(json.contains(abilityData, "Text")): text = json.get(abilityData, "Text")]

	[h: actionDiamonds = ""]
	[h, if(action == "1"): actionDiamonds = "&#9670;"]
	[h, if(action == "2"): actionDiamonds = "&#9670;&#9670;"]
	[h, if(action == "3"): actionDiamonds = "&#9670;&#9670;&#9670;"]
	[h: macroLabel = abilityName]
	[h, if(actionDiamonds != ""): macroLabel = abilityName + " <span style=" + decode("%22") + "color:black" + decode("%22") + ">" + actionDiamonds + "</span>"]

	[h: tooltipTraits = ""]
	[h: traitCount = json.length(traits)]
	[h, for(t, 0, traitCount), code: {
		[h: tooltipTrait = json.get(traits, t)]
		[h: tooltipTraits = listAppend(tooltipTraits, tooltipTrait, ", ")]
	}]

	[h: actionHtml = ""]
	[h, if(action == "1"): actionHtml = '<img height=15 width=15 src="asset://e7876556a71025c1a63de5aa47553c43" />']
	[h, if(action == "2"): actionHtml = '<img height=13 width=20 src="asset://6d8ac5fce8e04fc97996d921acea5499" />']
	[h, if(action == "3"): actionHtml = '<img height=15 width=31 src="asset://ba42444f6e7189a4450a18edb9aea022" />']
	[h, if(action == "R"): actionHtml = '<img height=18 width=18 src="asset://350ae7b3054be8a96f62ddf0f13de5ba" />']
	[h, if(action == "F"): actionHtml = '<img height=15 width=15 src="asset://70ad3250dee31e0250014fb92ed1e159" />']
	[h, if(action != "" && action != "1" && action != "2" && action != "3" && action != "R" && action != "F"): actionHtml = action]

	[h: abilityName = replace(abilityName, "'", "&#39;")]
	[h: trigger = replace(trigger, "'", "&#39;")]
	[h: requirements = replace(requirements, "'", "&#39;")]
	[h: action = replace(action, "'", "&#39;")]
	[h: text = replace(text, "'", "&#39;")]
	[h: tooltipTraits = replace(tooltipTraits, "'", "&#39;")]
	[h: traitsList = json.toList(traits)]
	[h: traitsList = replace(traitsList, "'", "")]

	[h: macroTooltip = "<html><div style=" + decode("%22") + "width: 300px;" + decode("%22") + "><b>" + abilityName + "</b>  " + actionHtml]
	[h, if(tooltipTraits != ""): macroTooltip = macroTooltip + " (" + tooltipTraits + ")"]
	[h, if(trigger != ""): macroTooltip = macroTooltip + "<br><b>Trigger</b> " + trigger]
	[h, if(requirements != ""): macroTooltip = macroTooltip + "<br><b>Requirements</b> " + requirements]
	[h, if(text != ""): macroTooltip = macroTooltip + "<br>" + text]
	[h: macroTooltip = macroTooltip + "</div></html>"]

	[h: macroCommand = "[h:Name='" + abilityName + "']"]
	[h: macroCommand = macroCommand + "[h:FeatLevel='" + featLevel + "']"]
	[h: macroCommand = macroCommand + "[h:TraitsList='" + traitsList + "']"]
	[h: macroCommand = macroCommand + "[h:Traits='[]']"]
	[h: macroCommand = macroCommand + "[h, if(TraitsList != ''), code:{[h, foreach(TraitName, TraitsList), code:{[h:TraitName=replace(TraitName, decode('%27'), '')][h:Traits=json.append(Traits,TraitName)]}]}]"]
	[h: macroCommand = macroCommand + "[h:Trigger='" + trigger + "']"]
	[h: macroCommand = macroCommand + "[h:Requirements='" + requirements + "']"]
	[h: macroCommand = macroCommand + "[h:Action='" + action + "']"]
	[h: macroCommand = macroCommand + "[h:Text='" + text + "']"]
	[h: macroCommand = macroCommand + "[h:FeatData=json.set('{}','Name',Name,'FeatLevel',FeatLevel,'Traits',Traits,'Trigger',Trigger,'Requirements',Requirements,'Action',Action,'Text',Text)]"]
	[h: macroCommand = macroCommand + "[h, macro('_Feat@Lib:AON'):FeatData]"]
	[h: macroCommand = macroCommand + "[g,r: macro.return]"]

	[h: existingIndexes = ""]
	[h, token(tokenID): existingIndexes = getMacroIndexes(macroLabel)]
	[h: macroProps = json.set("{}", "label", macroLabel, "command", macroCommand, "autoExecute", 1, "playerEditable", 1, "group", macroGroup, "tooltip", macroTooltip)]
	[h, if(existingIndexes == ""): createMacro(macroProps, tokenID)]
	[h, if(existingIndexes != ""), code: {
		[h: existingIndex = listGet(existingIndexes, 0)]
		[h, token(tokenID): setMacroProps(existingIndex, macroProps, "json")]
	}]
}]
