[h: args = macro.args]
[h: tokenID = args]
[h, if(args != "" && json.type(args) == "OBJECT" && json.contains(args, "tokenID")): tokenID = json.get(args, "tokenID")]

[h: assert(tokenID != "", "No token id passed to _AddParsedAttackMacros.", 0)]

[h: aonJson = getProperty("AON_JSON", tokenID)]
[h: assert(aonJson != "", "AON_JSON is blank.", 0)]
[h: assert(json.type(aonJson) == "OBJECT", "AON_JSON is not a JSON object.", 0)]
[h: assert(json.contains(aonJson, "Parsed"), "AON_JSON.Parsed is missing.", 0)]

[h: parsed = json.get(aonJson, "Parsed")]
[h: attacks = "[]"]
[h, if(json.contains(parsed, "Attacks")): attacks = json.get(parsed, "Attacks")]
[h: assert(json.type(attacks) == "ARRAY", "AON_JSON.Parsed.Attacks is not a JSON array.", 0)]

[h: attackCount = json.length(attacks)]
[h, for(i, 0, attackCount), code: {
	[h: attackData = json.get(attacks, i)]
	[h: attackName = "Attack"]
	[h, if(json.contains(attackData, "AttackName")): attackName = json.get(attackData, "AttackName")]
	[h: macroGroup = ""]

	[h: displayAttackName = upper(substring(attackName, 0, 1)) + substring(attackName, 1)]
	[h: attackType = ""]
	[h, if(json.contains(attackData, "AttackType")): attackType = json.get(attackData, "AttackType")]
	[h: attackModifier = ""]
	[h, if(json.contains(attackData, "AttackModifier")): attackModifier = json.get(attackData, "AttackModifier")]
	[h: damage = ""]
	[h, if(json.contains(attackData, "Damage")): damage = json.get(attackData, "Damage")]
	[h: damageType = ""]
	[h, if(json.contains(attackData, "DamageType")): damageType = json.get(attackData, "DamageType")]
	[h: damage2 = ""]
	[h, if(json.contains(attackData, "Damage2")): damage2 = json.get(attackData, "Damage2")]
	[h: damage2Type = ""]
	[h, if(json.contains(attackData, "Damage2Type")): damage2Type = json.get(attackData, "Damage2Type")]
	[h: effect = ""]
	[h, if(json.contains(attackData, "Effect")): effect = json.get(attackData, "Effect")]
	[h: action = ""]
	[h, if(json.contains(attackData, "Action")): action = json.get(attackData, "Action")]
	[h: applyAttackKeyword = 1]
	[h, if(json.contains(attackData, "ApplyAttackKeyword")): applyAttackKeyword = json.get(attackData, "ApplyAttackKeyword")]
	[h: actionDiamonds = ""]
	[h, if(action == "1"): actionDiamonds = "&#9670;"]
	[h, if(action == "2"): actionDiamonds = "&#9670;&#9670;"]
	[h, if(action == "3"): actionDiamonds = "&#9670;&#9670;&#9670;"]
	[h: macroLabel = attackName]
	[h, if(actionDiamonds != ""): macroLabel = attackName + " <span style=" + decode("%22") + "color:black" + decode("%22") + ">" + actionDiamonds + "</span>"]

	[h: macroTraits = "[]"]
	[h: attackTraits = "[]"]
	[h, if(json.contains(attackData, "Traits")): attackTraits = json.get(attackData, "Traits")]
	[h: macroTraits = attackTraits]
	[h, if(json.contains(macroTraits, "melee")): macroTraits = json.remove(macroTraits, json.indexOf(macroTraits, "melee"))]
	[h, if(json.contains(macroTraits, "ranged")): macroTraits = json.remove(macroTraits, json.indexOf(macroTraits, "ranged"))]

	[h: displayAttackName = replace(displayAttackName, "'", "&#39;")]
	[h: attackType = replace(attackType, "'", "&#39;")]
	[h: attackModifier = replace(attackModifier, "'", "&#39;")]
	[h: damage = replace(damage, "'", "&#39;")]
	[h: damageType = replace(damageType, "'", "&#39;")]
	[h: damage2 = replace(damage2, "'", "&#39;")]
	[h: damage2Type = replace(damage2Type, "'", "&#39;")]
	[h: effect = replace(effect, "'", "&#39;")]
	[h: action = replace(action, "'", "&#39;")]

	[h: macroCommand = "[h:AttackName='" + displayAttackName + "']"]
	[h: macroCommand = macroCommand + "[h:DamageTooltip='" + damage + "']"]
	[h: macroCommand = macroCommand + "[h:DamageRoll=eval(DamageTooltip)]"]
	[h: macroCommand = macroCommand + "[h:AttackType='" + attackType + "']"]
	[h: macroCommand = macroCommand + "[h:Traits='" + macroTraits + "']"]
	[h: macroCommand = macroCommand + "[h:AttackModifier='" + attackModifier + "']"]
	[h: macroCommand = macroCommand + "[h:Damage='" + damage + "']"]
	[h: macroCommand = macroCommand + "[h:DamageType='" + damageType + "']"]
	[h: macroCommand = macroCommand + "[h:Damage2='" + damage2 + "']"]
	[h: macroCommand = macroCommand + "[h:Damage2Type='" + damage2Type + "']"]
	[h: macroCommand = macroCommand + "[h:Effect='" + effect + "']"]
	[h: macroCommand = macroCommand + "[h:Action='" + action + "']"]
	[h: macroCommand = macroCommand + "[h:ApplyAttackKeyword=" + applyAttackKeyword + "]"]
	[h: macroCommand = macroCommand + "[h:AttackData=json.set('{}','AttackName',AttackName,'AttackType',AttackType,'Traits',Traits,'AttackModifier',AttackModifier,'Damage',Damage,'DamageType',DamageType,'Damage2',Damage2,'Damage2Type',Damage2Type,'Effect',Effect,'Action',Action,'ApplyAttackKeyword',ApplyAttackKeyword)]"]
	[h: macroCommand = macroCommand + "[macro('NPCSimpleAttack@Lib:Pf2'):AttackData]"]

	[h: existingIndexes = ""]
	[h, token(tokenID): existingIndexes = getMacroIndexes(macroLabel)]
	[h: macroProps = json.set("{}", "label", macroLabel, "command", macroCommand, "autoExecute", 1, "playerEditable", 1, "group", macroGroup)]
	[h, if(existingIndexes == ""): createMacro(macroProps, tokenID)]
	[h, if(existingIndexes != ""), code: {
		[h: existingIndex = listGet(existingIndexes, 0)]
		[h, token(tokenID): setMacroProps(existingIndex, macroProps, "json")]
	}]
}]
