[h: creatureData = macro.args]
[h: assert(creatureData != "", "No creature data passed to _ParseCreatureInfo.", 0)]
[h: assert(json.type(creatureData) == "OBJECT", "Creature data is not a JSON object.", 0)]

[h: rawMarkdown = ""]
[h, if(json.contains(creatureData, "markdown")): rawMarkdown = json.get(creatureData, "markdown")]
[h, if(rawMarkdown == "" && json.contains(creatureData, "text")): rawMarkdown = json.get(creatureData, "text")]
[h, if(rawMarkdown == "" && json.contains(creatureData, "description")): rawMarkdown = json.get(creatureData, "description")]
[h: rawMarkdown = replace(rawMarkdown, decode("%0D"), "")]

[h: recallStart = indexOf(rawMarkdown, "**[Recall Knowledge")]
[h, if(recallStart >= 0), code: {
	[h: recallRemainder = substring(rawMarkdown, recallStart)]
	[h: recallEnd = indexOf(recallRemainder, "</column>")]
	[h, if(recallEnd >= 0): recallBlock = substring(recallRemainder, 0, recallEnd)]
	[h, if(recallEnd < 0): recallBlock = recallRemainder]

	[h: recallBlock = replace(recallBlock, "\\]\\([^\\)]*\\)", "")]
	[h: recallBlock = replace(recallBlock, "\\[", "")]
	[h: recallBlock = replace(recallBlock, "\\]", "")]
	[h: recallBlock = replace(recallBlock, "\\*\\*", "")]
	[h: recallBlock = trim(recallBlock)]
}]

[h: recallKnowledge = "[]"]
[h: recallLines = json.fromList(recallBlock, decode("%0A"))]
[h: pendingName = ""]

[h, foreach(line, recallLines), code: {
	[h: line = trim(line)]
	[h: hasDC = indexOf(line, "DC") >= 0]
	[h: hasSkills = startsWith(line, "(")]
	[h: isName = line != "" && !hasDC && !hasSkills]

	[h, if(isName): pendingName = line]

	[h, if(hasSkills), code: {
		[h: skillEnd = indexOf(line, ")")]
		[h: skills = substring(line, 1, skillEnd)]
		[h: dc = trim(substring(line, indexOf(line, "DC") + 3))]
		[h: entry = json.set("{}", "Name", pendingName, "Skills", skills, "DC", dc)]
		[h: recallKnowledge = json.append(recallKnowledge, entry)]
		[h: pendingName = ""]
	}]

	[h, if(hasDC && !hasSkills), code: {
		[h: nameEnd = indexOf(line, ":")]
		[h: name = trim(substring(line, 0, nameEnd))]
		[h: dc = trim(substring(line, indexOf(line, "DC") + 3))]
		[h: entry = json.set("{}", "Name", name, "Skills", "", "DC", dc)]
		[h: recallKnowledge = json.append(recallKnowledge, entry)]
	}]
}]

[h: creatureInfoRaw = rawMarkdown]
[h: cutIndex = -1]
[h: markerList = "## Elite,## [Elite],### Print Stat Block,# ["]
[h: markerList = listAppend(markerList, "**Perception**")]
[h: markerList = listAppend(markerList, "**Skills**")]
[h: markerList = listAppend(markerList, "**Str**")]
[h: markerList = listAppend(markerList, "**AC**")]
[h: markerList = listAppend(markerList, "**HP**")]
[h: markerList = listAppend(markerList, "**[Recall Knowledge")]
[h: markerList = listAppend(markerList, "**Source**")]
[h: markerList = listAppend(markerList, "<title level=" + decode("%22") + "2" + decode("%22"))]
[h: markerList = listAppend(markerList, "<column gap=" + decode("%22") + "tiny" + decode("%22"))]
[h: markerList = listAppend(markerList, "**Speed**")]
[h: markerList = listAppend(markerList, "**Melee**")]
[h: markerList = listAppend(markerList, "**Ranged**")]
[h: markerList = listAppend(markerList, "**Spells**")]
[h: markerList = listAppend(markerList, "**Primal Innate Spells**")]
[h: markerList = listAppend(markerList, "**Arcane Innate Spells**")]
[h: markerList = listAppend(markerList, "**Divine Innate Spells**")]
[h: markerList = listAppend(markerList, "**Occult Innate Spells**")]
[h: markerList = listAppend(markerList, "**Items**")]
[h, foreach(marker, markerList), code: {
	[h: markerIndex = indexOf(creatureInfoRaw, marker)]
	[h, if(markerIndex >= 0 && (cutIndex == -1 || markerIndex < cutIndex)): cutIndex = markerIndex]
}]
[h, if(cutIndex > 0): creatureInfoRaw = substring(creatureInfoRaw, 0, cutIndex)]

[h: descriptionText = creatureInfoRaw]
[h: headingEnd = indexOf(descriptionText, decode("%0A"))]
[h, if(startsWith(descriptionText, "# ") && headingEnd >= 0): descriptionText = substring(descriptionText, headingEnd + 1)]
[h: descriptionText = replace(descriptionText, "<title[^>]*>[^<]*</title>", "")]
[h: descriptionText = replace(descriptionText, "<title[^>]*>", "")]
[h: descriptionText = replace(descriptionText, "</title>", "")]
[h: descriptionText = replace(descriptionText, "<row[^>]*>", "")]
[h: descriptionText = replace(descriptionText, "</row>", "")]
[h: descriptionText = replace(descriptionText, "<column[^>]*>", "")]
[h: descriptionText = replace(descriptionText, "</column>", "")]
[h: descriptionText = replace(descriptionText, "<image[^>]*>", "")]
[h: descriptionText = replace(descriptionText, "<traits[^>]*>", "")]
[h: descriptionText = replace(descriptionText, "</traits>", "")]
[h: descriptionText = replace(descriptionText, "<trait[^>]*>", "")]
[h: descriptionText = replace(descriptionText, "\\]\\([^\\)]*\\)", "")]
[h: descriptionText = replace(descriptionText, "\\[", "")]
[h: descriptionText = replace(descriptionText, "\\]", "")]
[h: descriptionText = replace(descriptionText, "(?m)^#+\\s*", "")]
[h: descriptionText = replace(descriptionText, "\\*\\*", "")]
[h: descriptionText = replace(descriptionText, "__", "")]
[h: descriptionText = replace(descriptionText, "\\r", "")]
[h: doubleBreak = decode("%0A") + decode("%0A")]
[h: tripleBreak = doubleBreak + decode("%0A")]
[h, while(indexOf(descriptionText, tripleBreak) >= 0): descriptionText = replace(descriptionText, tripleBreak, doubleBreak)]
[h: descriptionText = replace(descriptionText, decode("%0A") + decode("%0A"), "<br /><br />")]
[h: descriptionText = replace(descriptionText, decode("%0A"), "<br />")]
[h, while(startsWith(descriptionText, "<br />")): descriptionText = substring(descriptionText, 6)]
[h, while(endsWith(descriptionText, "<br />")): descriptionText = substring(descriptionText, 0, length(descriptionText)-6)]
[h: descriptionText = trim(descriptionText)]

[h: creatureInfo = json.set("{}", "DescriptionText", descriptionText, "RawMarkdown", creatureInfoRaw, "RecallKnowledge", recallKnowledge, "ParserVersion", "1.00", "ParseSource", "markdown")]

[macro.return = creatureInfo]