[h: creatureData = macro.args]
[h: attacks = "[]"]

[h: assert(creatureData != "", "No creature data passed to _ParseCreatureAttacks.", 0)]
[h: assert(json.type(creatureData) == "OBJECT", "Creature data passed to _ParseCreatureAttacks was not a JSON object.", 0)]

[h: creatureMarkdown = ""]
[h, if(json.contains(creatureData, "markdown")): creatureMarkdown = json.get(creatureData, "markdown")]

[h: searchText = creatureMarkdown]
[h: meleeLabel = "**Melee**"]
[h: rangedLabel = "**Ranged**"]
[h: damageLabel = "**Damage**"]
[h: actionLabel = "<actions string=" + decode("%22")]
[h: markdownUrlStart = decode("%5D") + "("]
[h: labelLength = 0]
[h: guard = 0]
[h: attackNumber = 0]

[h: attackBonusValues = ""]
[h, if(json.contains(creatureData, "attack_bonus")): attackBonusValues = json.get(creatureData, "attack_bonus")]
[h: attackBonusScaleValues = ""]
[h, if(json.contains(creatureData, "attack_bonus_scale")): attackBonusScaleValues = json.get(creatureData, "attack_bonus_scale")]
[h: attackBonusScaleNumberValues = ""]
[h, if(json.contains(creatureData, "attack_bonus_scale_number")): attackBonusScaleNumberValues = json.get(creatureData, "attack_bonus_scale_number")]
[h: strikeDamageAverageValues = ""]
[h, if(json.contains(creatureData, "strike_damage_average")): strikeDamageAverageValues = json.get(creatureData, "strike_damage_average")]
[h: strikeDamageScaleValues = ""]
[h, if(json.contains(creatureData, "strike_damage_scale")): strikeDamageScaleValues = json.get(creatureData, "strike_damage_scale")]
[h: strikeDamageScaleNumberValues = ""]
[h, if(json.contains(creatureData, "strike_damage_scale_number")): strikeDamageScaleNumberValues = json.get(creatureData, "strike_damage_scale_number")]

[h: meleeIndex = indexOf(searchText, meleeLabel)]
[h: rangedIndex = indexOf(searchText, rangedLabel)]

[h, while((meleeIndex >= 0 || rangedIndex >= 0) && guard < 20), code: {
	[h: attackType = "Melee"]
	[h: attackStart = meleeIndex]
	[h: activeLabel = meleeLabel]
	[h, if(attackStart < 0 || (rangedIndex >= 0 && rangedIndex < attackStart)), code: {
		[h: attackType = "Ranged"]
		[h: attackStart = rangedIndex]
		[h: activeLabel = rangedLabel]
	}]

	[h: labelLength = length(activeLabel)]
	[h: afterLabel = substring(searchText, attackStart + labelLength)]
	[h: nextMelee = indexOf(afterLabel, meleeLabel)]
	[h: nextRanged = indexOf(afterLabel, rangedLabel)]
	[h: attackEnd = length(searchText)]
	[h, if(nextMelee >= 0): attackEnd = attackStart + labelLength + nextMelee]
	[h, if(nextRanged >= 0 && attackStart + labelLength + nextRanged < attackEnd): attackEnd = attackStart + labelLength + nextRanged]

	[h: attackBlock = substring(searchText, attackStart, attackEnd)]
	[h: traits = json.append("[]", lower(attackType))]

	[h: actionText = ""]
	[h: actionStart = indexOf(attackBlock, actionLabel)]
	[h, if(actionStart >= 0), code: {
		[h: actionRemainder = substring(attackBlock, actionStart + length(actionLabel))]
		[h: actionEnd = indexOf(actionRemainder, decode("%22"))]
		[h, if(actionEnd >= 0): actionText = substring(actionRemainder, 0, actionEnd)]
	}]

	[h: attackText = ""]
	[h: actionClose = indexOf(attackBlock, "/>")]
	[h: damageStart = indexOf(attackBlock, damageLabel)]
	[h, if(actionClose >= 0 && damageStart > actionClose), code: {
		[h: attackText = substring(attackBlock, actionClose + 2, damageStart)]
		[h: attackText = replace(attackText, decode("%0D"), "")]
		[h: attackText = trim(replace(attackText, decode("%0A"), " "))]
	}]

	[h: traitText = ""]
	[h: traitStart = indexOf(attackText, "(")]
	[h: traitEnd = lastIndexOf(attackText, ")")]
	[h, if(traitStart >= 0 && traitEnd > traitStart): traitText = substring(attackText, traitStart + 1, traitEnd)]
	[h: traitRemainder = traitText]
	[h, for(traitGuard, 0, 20), code: {
		[h: linkStart = indexOf(traitRemainder, decode("%5B"))]
		[h: linkEnd = indexOf(traitRemainder, decode("%5D"))]
		[h: traitName = ""]
		[h, if(linkStart >= 0 && linkEnd > linkStart): traitName = substring(traitRemainder, linkStart + 1, linkEnd)]
		[h, if(linkStart >= 0 && traitName != ""): traits = json.append(traits, lower(traitName))]
		[h, if(linkStart >= 0 && linkEnd >= 0): traitRemainder = substring(traitRemainder, linkEnd + 1)]
		[h, if(linkStart < 0 || linkEnd < 0): traitRemainder = ""]
	}]

	[h: cleanAttackText = attackText]
	[h: cleanLinkStart = indexOf(cleanAttackText, decode("%5B"))]
	[h, for(cleanGuard, 0, 20), code: {
		[h: cleanLinkEnd = indexOf(cleanAttackText, decode("%5D"))]
		[h: cleanUrlStart = indexOf(cleanAttackText, markdownUrlStart)]
		[h: cleanUrlEnd = indexOf(cleanAttackText, ")")]
		[h: cleanLabel = ""]
		[h, if(cleanLinkStart >= 0 && cleanLinkEnd > cleanLinkStart): cleanLabel = substring(cleanAttackText, cleanLinkStart + 1, cleanLinkEnd)]
		[h, if(cleanLinkStart >= 0 && cleanLabel != "" && cleanUrlStart == cleanLinkEnd && cleanUrlEnd > cleanUrlStart): cleanAttackText = substring(cleanAttackText, 0, cleanLinkStart) + cleanLabel + substring(cleanAttackText, cleanUrlEnd + 1)]
		[h, if(cleanLinkStart >= 0 && (cleanLabel == "" || cleanUrlStart != cleanLinkEnd || cleanUrlEnd <= cleanUrlStart)): cleanLinkStart = -1]
		[h, if(cleanLinkStart >= 0): cleanLinkStart = indexOf(cleanAttackText, decode("%5B"))]
	}]
	[h: attackText = cleanAttackText]

	[h: damageText = ""]
	[h, if(damageStart >= 0), code: {
		[h: damageText = substring(attackBlock, damageStart + length(damageLabel))]
		[h: damageText = replace(damageText, decode("%0D"), "")]
		[h: damageLineEnd = indexOf(damageText, decode("%0A%0A"))]
		[h, if(damageLineEnd >= 0): damageText = substring(damageText, 0, damageLineEnd)]
		[h: damageText = trim(replace(damageText, decode("%0A"), " "))]
	}]

	[h: rawBlock = replace(attackBlock, decode("%0D"), "")]
	[h: rawDamageStart = indexOf(rawBlock, damageLabel)]
	[h, if(rawDamageStart >= 0), code: {
		[h: rawDamageText = substring(rawBlock, rawDamageStart + length(damageLabel))]
		[h: rawDamageEnd = indexOf(rawDamageText, decode("%0A%0A"))]
		[h, if(rawDamageEnd >= 0): rawBlock = substring(rawBlock, 0, rawDamageStart + length(damageLabel) + rawDamageEnd)]
	}]
	[h: rawBlock = trim(replace(rawBlock, decode("%0A"), " "))]

	[h: attackName = attackText]
	[h: attackModifier = ""]
	[h: modifierPlus = indexOf(attackText, " +")]
	[h: modifierMinus = indexOf(attackText, " -")]
	[h: modifierStart = modifierPlus]
	[h, if(modifierStart < 0 || (modifierMinus >= 0 && modifierMinus < modifierStart)): modifierStart = modifierMinus]
	[h, if(modifierStart >= 0): attackName = trim(substring(attackText, 0, modifierStart))]
	[h: modifierRemainder = ""]
	[h, if(modifierStart >= 0): modifierRemainder = substring(attackText, modifierStart + 1)]
	[h: modifierEnd = indexOf(modifierRemainder, " ")]
	[h, if(modifierEnd < 0): modifierEnd = indexOf(modifierRemainder, "(")]
	[h, if(modifierEnd < 0): modifierEnd = indexOf(modifierRemainder, ",")]
	[h, if(modifierEnd < 0): modifierEnd = length(modifierRemainder)]
	[h, if(modifierRemainder != ""): attackModifier = substring(modifierRemainder, 0, modifierEnd)]
	[h: attackModifier = replace(attackModifier, decode("%5C%2B"), "")]
	[h: attackModifier = trim(replace(attackModifier, ",", ""))]

	[h: actionValue = actionText]
	[h, if(lower(actionText) == "single action"): actionValue = "1"]
	[h, if(lower(actionText) == "two actions"): actionValue = "2"]
	[h, if(lower(actionText) == "three actions"): actionValue = "3"]
	[h, if(lower(actionText) == "reaction"): actionValue = "R"]
	[h, if(lower(actionText) == "free action"): actionValue = "F"]

	[h: damage = ""]
	[h: damageType = ""]
	[h: damage2 = ""]
	[h: damage2Type = ""]
	[h: effect = ""]
	[h: damageRemainder = damageText]
	[h: damageSpace = indexOf(damageRemainder, " ")]
	[h, if(damageSpace >= 0): damage = substring(damageRemainder, 0, damageSpace)]
	[h, if(damageSpace < 0): damage = damageRemainder]
	[h, if(damageSpace >= 0): damageRemainder = trim(substring(damageRemainder, damageSpace + 1))]
	[h: damageTypeSpace = indexOf(damageRemainder, " ")]
	[h, if(damageTypeSpace >= 0): damageType = substring(damageRemainder, 0, damageTypeSpace)]
	[h, if(damageTypeSpace < 0): damageType = damageRemainder]
	[h, if(damageTypeSpace >= 0): damageRemainder = trim(substring(damageRemainder, damageTypeSpace + 1))]
	[h, if(damageTypeSpace < 0): damageRemainder = ""]
	[h, if(startsWith(damageRemainder, "plus ")): damageRemainder = substring(damageRemainder, 5)]
	[h: secondDamageSpace = indexOf(damageRemainder, " ")]
	[h: secondDamageToken = damageRemainder]
	[h, if(secondDamageSpace >= 0): secondDamageToken = substring(damageRemainder, 0, secondDamageSpace)]
	[h: secondDamageFirstChar = ""]
	[h, if(length(secondDamageToken) > 0): secondDamageFirstChar = substring(secondDamageToken, 0, 1)]
	[h: secondDamageStartsNumber = 0]
	[h, if(listFind("0,1,2,3,4,5,6,7,8,9", secondDamageFirstChar) >= 0): secondDamageStartsNumber = 1]
	[h, if(secondDamageStartsNumber == 1 && indexOf(secondDamageToken, "d") > 0): damage2 = secondDamageToken]
	[h: secondRemainder = ""]
	[h, if(secondDamageSpace >= 0): secondRemainder = trim(substring(damageRemainder, secondDamageSpace + 1))]
	[h, if(damage2 != ""): damageRemainder = secondRemainder]
	[h, if(damage2 == "" && secondDamageStartsNumber == 1 && startsWith(secondRemainder, "persistent ")), code: {
		[h: damage2 = secondDamageToken]
		[h: persistentRemainder = substring(secondRemainder, 11)]
		[h: persistentTypeEnd = indexOf(persistentRemainder, " ")]
		[h, if(persistentTypeEnd >= 0): damage2Type = "persistent " + substring(persistentRemainder, 0, persistentTypeEnd)]
		[h, if(persistentTypeEnd < 0): damage2Type = "persistent " + persistentRemainder]
		[h, if(persistentTypeEnd >= 0): damageRemainder = trim(substring(persistentRemainder, persistentTypeEnd + 1))]
		[h, if(persistentTypeEnd < 0): damageRemainder = ""]
		[h, if(damageRemainder == "damage"): damageRemainder = ""]
	}]
	[h: secondDamageTypeSpace = indexOf(damageRemainder, " ")]
	[h, if(damage2 != "" && damage2Type == "" && secondDamageTypeSpace >= 0): damage2Type = substring(damageRemainder, 0, secondDamageTypeSpace)]
	[h, if(damage2 != "" && damage2Type == "" && secondDamageTypeSpace < 0): damage2Type = damageRemainder]
	[h, if(damage2 != "" && damage2Type != "" && secondDamageTypeSpace >= 0): effect = trim(substring(damageRemainder, secondDamageTypeSpace + 1))]
	[h, if(damage2 == ""): effect = damageRemainder]

	[h: attackObj = json.set("{}", "Index", attackNumber, "Type", attackType, "ActionText", actionText, "Action", actionValue + "", "AttackName", attackName, "AttackType", attackType, "AttackModifier", attackModifier + "", "AttackText", attackText, "Traits", traits, "DamageText", damageText, "Damage", damage, "DamageType", damageType, "Damage2", damage2, "Damage2Type", damage2Type, "Effect", effect, "ApplyAttackKeyword", 1, "RawBlock", rawBlock)]
	[h, if(json.type(attackBonusValues) == "ARRAY" && json.length(attackBonusValues) > attackNumber): attackObj = json.set(attackObj, "AttackBonus", json.get(attackBonusValues, attackNumber))]
	[h, if(json.type(attackBonusScaleValues) == "ARRAY" && json.length(attackBonusScaleValues) == 1): attackObj = json.set(attackObj, "AttackBonusScale", json.get(attackBonusScaleValues, 0))]
	[h, if(json.type(attackBonusScaleValues) == "ARRAY" && json.length(attackBonusScaleValues) > attackNumber): attackObj = json.set(attackObj, "AttackBonusScale", json.get(attackBonusScaleValues, attackNumber))]
	[h, if(json.type(attackBonusScaleNumberValues) == "ARRAY" && json.length(attackBonusScaleNumberValues) == 1): attackObj = json.set(attackObj, "AttackBonusScaleNumber", json.get(attackBonusScaleNumberValues, 0))]
	[h, if(json.type(attackBonusScaleNumberValues) == "ARRAY" && json.length(attackBonusScaleNumberValues) > attackNumber): attackObj = json.set(attackObj, "AttackBonusScaleNumber", json.get(attackBonusScaleNumberValues, attackNumber))]
	[h, if(json.type(strikeDamageAverageValues) == "ARRAY" && json.length(strikeDamageAverageValues) > attackNumber): attackObj = json.set(attackObj, "StrikeDamageAverage", json.get(strikeDamageAverageValues, attackNumber))]
	[h, if(json.type(strikeDamageScaleValues) == "ARRAY" && json.length(strikeDamageScaleValues) > attackNumber): attackObj = json.set(attackObj, "StrikeDamageScale", json.get(strikeDamageScaleValues, attackNumber))]
	[h, if(json.type(strikeDamageScaleNumberValues) == "ARRAY" && json.length(strikeDamageScaleNumberValues) > attackNumber): attackObj = json.set(attackObj, "StrikeDamageScaleNumber", json.get(strikeDamageScaleNumberValues, attackNumber))]
	[h: attacks = json.append(attacks, attackObj)]

	[h: searchText = substring(searchText, attackEnd)]
	[h: meleeIndex = indexOf(searchText, meleeLabel)]
	[h: rangedIndex = indexOf(searchText, rangedLabel)]
	[h: attackNumber = attackNumber + 1]
	[h: guard = guard + 1]
}]

[macro.return = attacks]
