[h: creatureData = macro.args]
[h: abilities = "[]"]

[h: assert(creatureData != "", "No creature data passed to _ParseCreatureAbilities.", 0)]
[h: assert(json.type(creatureData) == "OBJECT", "Creature data passed to _ParseCreatureAbilities was not a JSON object.", 0)]

[h: creatureMarkdown = ""]
[h, if(json.contains(creatureData, "markdown")): creatureMarkdown = json.get(creatureData, "markdown")]
[h: creatureMarkdown = replace(creatureMarkdown, decode("%0D"), "")]

[h: abilityNames = ""]
[h, if(json.contains(creatureData, "creature_ability")): abilityNames = json.get(creatureData, "creature_ability")]
[h: abilityCount = 0]
[h, if(json.type(abilityNames) == "ARRAY"): abilityCount = json.length(abilityNames)]

[h: actionLabel = "<actions string=" + decode("%22")]
[h: paragraphBreak = decode("%0A%0A")]
[h: markdownUrlStart = decode("%5D") + "("]
[h: featLevel = ""]
[h, if(json.contains(creatureData, "level")): featLevel = json.get(creatureData, "level") + ""]

[h, for(i, 0, abilityCount), code: {
	[h: abilityName = json.get(abilityNames, i)]
	[h: plainLabel = "**" + abilityName + "**"]
	[h: linkLabel = "**" + decode("%5B") + abilityName + decode("%5D")]
	[h: plainIndex = indexOf(creatureMarkdown, plainLabel)]
	[h: linkIndex = indexOf(creatureMarkdown, linkLabel)]
	[h: abilityStart = plainIndex]
	[h, if(abilityStart < 0 || (linkIndex >= 0 && linkIndex < abilityStart)): abilityStart = linkIndex]

	[h: afterStart = ""]
	[h, if(abilityStart >= 0): afterStart = substring(creatureMarkdown, abilityStart)]
	[h: abilityEnd = indexOf(afterStart, paragraphBreak)]
	[h, if(abilityEnd < 0): abilityEnd = length(afterStart)]
	[h: abilityBlock = substring(afterStart, 0, abilityEnd)]

	[h: rawBlock = trim(replace(abilityBlock, decode("%0A"), " "))]

	[h: headingEnd = -1]
	[h: afterOpen = ""]
	[h, if(length(abilityBlock) > 2): afterOpen = substring(abilityBlock, 2)]
	[h: closeHeading = indexOf(afterOpen, "**")]
	[h, if(closeHeading >= 0): headingEnd = closeHeading + 4]
	[h: afterHeading = abilityBlock]
	[h, if(headingEnd >= 0): afterHeading = substring(abilityBlock, headingEnd)]

	[h: actionText = ""]
	[h: actionStart = indexOf(abilityBlock, actionLabel)]
	[h: actionRemainder = ""]
	[h, if(actionStart >= 0): actionRemainder = substring(abilityBlock, actionStart + length(actionLabel))]
	[h: actionEnd = indexOf(actionRemainder, decode("%22"))]
	[h, if(actionEnd >= 0): actionText = substring(actionRemainder, 0, actionEnd)]

	[h: traitSearchText = afterHeading]
	[h: actionClose = indexOf(afterHeading, "/>")]
	[h, if(actionClose >= 0): traitSearchText = substring(afterHeading, actionClose + 2)]
	[h: traitsText = ""]
	[h: traitsStart = indexOf(traitSearchText, "(")]
	[h: traitsEnd = indexOf(traitSearchText, "))")]
	[h, if(traitsEnd >= 0): traitsEnd = traitsEnd + 1]
	[h, if(traitsEnd < 0): traitsEnd = indexOf(traitSearchText, ")")]
	[h, if(traitsStart >= 0 && traitsEnd > traitsStart): traitsText = substring(traitSearchText, traitsStart + 1, traitsEnd)]

	[h: descriptionText = afterHeading]
	[h, if(traitsEnd > traitsStart && traitsStart >= 0): descriptionText = substring(traitSearchText, traitsEnd + 1)]
	[h, if(traitsStart < 0 && actionClose >= 0): descriptionText = substring(afterHeading, actionClose + 2)]
	[h: descriptionText = trim(replace(descriptionText, decode("%0A"), " "))]

	[h: traits = "[]"]
	[h: traitRemainder = traitsText]
	[h, for(traitGuard, 0, 20), code: {
		[h: linkStart = indexOf(traitRemainder, decode("%5B"))]
		[h: linkEnd = indexOf(traitRemainder, decode("%5D"))]
		[h: traitName = ""]
		[h, if(linkStart >= 0 && linkEnd > linkStart): traitName = substring(traitRemainder, linkStart + 1, linkEnd)]
		[h, if(linkStart >= 0 && traitName != ""): traits = json.append(traits, traitName)]
		[h, if(linkStart >= 0 && linkEnd >= 0): traitRemainder = substring(traitRemainder, linkEnd + 1)]
		[h, if(linkStart < 0 || linkEnd < 0): traitRemainder = ""]
	}]

	[h: cleanTraitsText = traitsText]
	[h: cleanTraitLinkStart = indexOf(cleanTraitsText, decode("%5B"))]
	[h, for(cleanTraitGuard, 0, 20), code: {
		[h: cleanTraitAfterLink = ""]
		[h, if(cleanTraitLinkStart >= 0): cleanTraitAfterLink = substring(cleanTraitsText, cleanTraitLinkStart)]
		[h: cleanTraitLinkEnd = indexOf(cleanTraitAfterLink, decode("%5D"))]
		[h: cleanTraitUrlStart = indexOf(cleanTraitAfterLink, markdownUrlStart)]
		[h: cleanTraitUrlEnd = indexOf(cleanTraitAfterLink, ")")]
		[h: cleanTraitLabel = ""]
		[h, if(cleanTraitLinkStart >= 0 && cleanTraitLinkEnd > 0): cleanTraitLabel = substring(cleanTraitAfterLink, 1, cleanTraitLinkEnd)]
		[h, if(cleanTraitLinkStart >= 0 && cleanTraitLabel != "" && cleanTraitUrlStart == cleanTraitLinkEnd && cleanTraitUrlEnd > cleanTraitUrlStart): cleanTraitsText = substring(cleanTraitsText, 0, cleanTraitLinkStart) + cleanTraitLabel + substring(cleanTraitsText, cleanTraitLinkStart + cleanTraitUrlEnd + 1)]
		[h, if(cleanTraitLinkStart >= 0 && (cleanTraitLabel == "" || cleanTraitUrlStart != cleanTraitLinkEnd || cleanTraitUrlEnd <= cleanTraitUrlStart)): cleanTraitLinkStart = -1]
		[h, if(cleanTraitLinkStart >= 0): cleanTraitLinkStart = indexOf(cleanTraitsText, decode("%5B"))]
	}]

	[h: cleanText = descriptionText]
	[h: cleanLinkStart = indexOf(cleanText, decode("%5B"))]
	[h, for(cleanGuard, 0, 50), code: {
		[h: cleanAfterLink = ""]
		[h, if(cleanLinkStart >= 0): cleanAfterLink = substring(cleanText, cleanLinkStart)]
		[h: cleanLinkEnd = indexOf(cleanAfterLink, decode("%5D"))]
		[h: cleanUrlStart = indexOf(cleanAfterLink, markdownUrlStart)]
		[h: cleanUrlEnd = indexOf(cleanAfterLink, ")")]
		[h: cleanLabel = ""]
		[h, if(cleanLinkStart >= 0 && cleanLinkEnd > 0): cleanLabel = substring(cleanAfterLink, 1, cleanLinkEnd)]
		[h, if(cleanLinkStart >= 0 && cleanLabel != "" && cleanUrlStart == cleanLinkEnd && cleanUrlEnd > cleanUrlStart): cleanText = substring(cleanText, 0, cleanLinkStart) + cleanLabel + substring(cleanText, cleanLinkStart + cleanUrlEnd + 1)]
		[h, if(cleanLinkStart >= 0 && (cleanLabel == "" || cleanUrlStart != cleanLinkEnd || cleanUrlEnd <= cleanUrlStart)): cleanLinkStart = -1]
		[h, if(cleanLinkStart >= 0): cleanLinkStart = indexOf(cleanText, decode("%5B"))]
	}]

	[h: actionValue = actionText]
	[h, if(lower(actionText) == "single action"): actionValue = "1"]
	[h, if(lower(actionText) == "two actions"): actionValue = "2"]
	[h, if(lower(actionText) == "three actions"): actionValue = "3"]
	[h, if(lower(actionText) == "reaction"): actionValue = "R"]
	[h, if(lower(actionText) == "free action"): actionValue = "F"]

	[h: trigger = ""]
	[h: requirements = ""]

	[h: abilityObj = json.set("{}", "Index", i, "Name", abilityName, "FeatLevel", featLevel, "Traits", traits, "Trigger", trigger, "Requirements", requirements, "Action", actionValue + "", "ActionText", actionText, "Text", cleanText, "TraitsText", cleanTraitsText, "DescriptionText", cleanText, "RawBlock", rawBlock)]
	[h, if(abilityStart >= 0): abilities = json.append(abilities, abilityObj)]
}]

[macro.return = abilities]
