[h: creatureData = macro.args]
[h: assert(creatureData != "", "No creature data passed to _ParseCreatureInfo.", 0)]
[h: assert(json.type(creatureData) == "OBJECT", "Creature data is not a JSON object.", 0)]

[h: rawMarkdown = ""]
[h, if(json.contains(creatureData, "markdown")): rawMarkdown = json.get(creatureData, "markdown")]
[h, if(rawMarkdown == "" && json.contains(creatureData, "text")): rawMarkdown = json.get(creatureData, "text")]
[h, if(rawMarkdown == "" && json.contains(creatureData, "description")): rawMarkdown = json.get(creatureData, "description")]
[h: rawMarkdown = replace(rawMarkdown, decode("%0D"), "")]

[h: creatureInfoRaw = rawMarkdown]
[h: cutIndex = -1]
[h: markerList = "## Elite,## [Elite],### Print Stat Block,# ["]
[h: markerList = listAppend(markerList, "**Perception**")]
[h: markerList = listAppend(markerList, "**Skills**")]
[h: markerList = listAppend(markerList, "**Str**")]
[h: markerList = listAppend(markerList, "**AC**")]
[h: markerList = listAppend(markerList, "**HP**")]
[h: markerList = listAppend(markerList, "**[Recall Knowledge")]
[h: markerList = listAppend(markerList, "**Source**")]
[h: markerList = listAppend(markerList, "<title level=" + decode("%22") + "2" + decode("%22"))]
[h: markerList = listAppend(markerList, "<column gap=" + decode("%22") + "tiny" + decode("%22"))]
[h: markerList = listAppend(markerList, "**Speed**")]
[h: markerList = listAppend(markerList, "**Melee**")]
[h: markerList = listAppend(markerList, "**Ranged**")]
[h: markerList = listAppend(markerList, "**Spells**")]
[h: markerList = listAppend(markerList, "**Primal Innate Spells**")]
[h: markerList = listAppend(markerList, "**Arcane Innate Spells**")]
[h: markerList = listAppend(markerList, "**Divine Innate Spells**")]
[h: markerList = listAppend(markerList, "**Occult Innate Spells**")]
[h: markerList = listAppend(markerList, "**Items**")]
[h, foreach(marker, markerList), code: {
	[h: markerIndex = indexOf(creatureInfoRaw, marker)]
	[h, if(markerIndex >= 0 && (cutIndex == -1 || markerIndex < cutIndex)): cutIndex = markerIndex]
}]
[h, if(cutIndex > 0): creatureInfoRaw = substring(creatureInfoRaw, 0, cutIndex)]

[h: descriptionText = creatureInfoRaw]
[h: headingEnd = indexOf(descriptionText, decode("%0A"))]
[h, if(startsWith(descriptionText, "# ") && headingEnd >= 0): descriptionText = substring(descriptionText, headingEnd + 1)]
[h: descriptionText = replace(descriptionText, "<title[^>]*>[^<]*</title>", "")]
[h: descriptionText = replace(descriptionText, "<title[^>]*>", "")]
[h: descriptionText = replace(descriptionText, "</title>", "")]
[h: descriptionText = replace(descriptionText, "<row[^>]*>", "")]
[h: descriptionText = replace(descriptionText, "</row>", "")]
[h: descriptionText = replace(descriptionText, "<column[^>]*>", "")]
[h: descriptionText = replace(descriptionText, "</column>", "")]
[h: descriptionText = replace(descriptionText, "<image[^>]*>", "")]
[h: descriptionText = replace(descriptionText, "<traits[^>]*>", "")]
[h: descriptionText = replace(descriptionText, "</traits>", "")]
[h: descriptionText = replace(descriptionText, "<trait[^>]*>", "")]
[h: descriptionText = replace(descriptionText, "\\]\\([^\\)]*\\)", "")]
[h: descriptionText = replace(descriptionText, "\\[", "")]
[h: descriptionText = replace(descriptionText, "\\]", "")]
[h: descriptionText = replace(descriptionText, "(?m)^#+\\s*", "")]
[h: descriptionText = replace(descriptionText, "\\*\\*", "")]
[h: descriptionText = replace(descriptionText, "__", "")]
[h: descriptionText = replace(descriptionText, "\\r", "")]
[h: doubleBreak = decode("%0A") + decode("%0A")]
[h: tripleBreak = doubleBreak + decode("%0A")]
[h, while(indexOf(descriptionText, tripleBreak) >= 0): descriptionText = replace(descriptionText, tripleBreak, doubleBreak)]
[h: descriptionText = trim(descriptionText)]

[h: creatureInfo = json.set("{}", "DescriptionText", descriptionText, "RawMarkdown", creatureInfoRaw, "ParserVersion", "1.00", "ParseSource", "markdown")]

[macro.return = creatureInfo]