[h: args = macro.args]
[h: tokenID = json.get(args, "tokenID")]
[h: creatureData = json.get(args, "creatureData")]
[h: aonURL = json.get(args, "aonURL")]
[h: aonImageURL = json.get(args, "aonImageURL")]
[h: creatureID = json.get(args, "creatureID")]
[h: aonCreatureNumber = json.get(args, "aonCreatureNumber")]

[h: assert(tokenID != "", "No token id passed to _SetCreatureProperties.", 0)]
[h: assert(creatureData != "", "No creature data passed to _SetCreatureProperties.", 0)]
[h: assert(json.type(creatureData) == "OBJECT", "Creature data passed to _SetCreatureProperties was not a JSON object.", 0)]
[h, if(creatureID == "" && json.contains(creatureData, "id")): creatureID = json.get(creatureData, "id")]
[h, if(aonCreatureNumber == "" && creatureID != ""), code: {
	[h: idSeparator = indexOf(creatureID, "-")]
	[h, if(idSeparator >= 0): aonCreatureNumber = substring(creatureID, idSeparator + 1)]
}]
[h: importerVersion = "1.00"]
[h: manualReviewNeeded = 1]
[h: cInfo = getInfo("client")]
[h: importDate = json.get(cInfo,"timeDate")]
[h: metadata = json.set("{}", "SourceID", creatureID, "AONID", aonCreatureNumber, "Type", "Creature", "Source", "AoN", "URL", aonURL, "ImporterVersion", importerVersion, "ImportDate", importDate)]
[h: parsed = "{}"]
[h: aonJson = json.set("{}", "Metadata", metadata, "Parsed", parsed)]

[h: setPropertyType("NPC", tokenID)]
[h, if(json.contains(creatureData, "level")): setProperty("Lvl", json.get(creatureData, "level"), tokenID)]
[h, if(json.contains(creatureData, "strength")): setProperty("Str", json.get(creatureData, "strength"), tokenID)]
[h, if(json.contains(creatureData, "dexterity")): setProperty("Dex", json.get(creatureData, "dexterity"), tokenID)]
[h, if(json.contains(creatureData, "constitution")): setProperty("Con", json.get(creatureData, "constitution"), tokenID)]
[h, if(json.contains(creatureData, "intelligence")): setProperty("Int", json.get(creatureData, "intelligence"), tokenID)]
[h, if(json.contains(creatureData, "wisdom")): setProperty("Wis", json.get(creatureData, "wisdom"), tokenID)]
[h, if(json.contains(creatureData, "charisma")): setProperty("Cha", json.get(creatureData, "charisma"), tokenID)]
[h, if(json.contains(creatureData, "hp_raw")): setProperty("HP", json.get(creatureData, "hp_raw"), tokenID)]
[h, if(json.contains(creatureData, "hp_raw")): setProperty("MaxHP", json.get(creatureData, "hp_raw"), tokenID)]
[h, if(json.contains(creatureData, "ac")): setProperty("AC", json.get(creatureData, "ac"), tokenID)]
[h, if(json.contains(creatureData, "fortitude_save")): setProperty("Fortitude", json.get(creatureData, "fortitude_save"), tokenID)]
[h, if(json.contains(creatureData, "reflex_save")): setProperty("Reflex", json.get(creatureData, "reflex_save"), tokenID)]
[h, if(json.contains(creatureData, "will_save")): setProperty("Will", json.get(creatureData, "will_save"), tokenID)]
[h, if(json.contains(creatureData, "perception")): setProperty("Perception", json.get(creatureData, "perception"), tokenID)]
[h, if(json.contains(creatureData, "speed_markdown")): setProperty("Speed", json.get(creatureData, "speed_markdown"), tokenID)]

[h: traitText = ""]
[h: creatureTraits = ""]
[h, if(json.contains(creatureData, "trait")): creatureTraits = json.get(creatureData, "trait")]
[h: traitCount = 0]
[h, if(json.type(creatureTraits) == "ARRAY"): traitCount = json.length(creatureTraits)]
[h, for(i, 0, traitCount), code: {
	[h: traitName = json.get(creatureTraits, i)]
	[h: traitText = traitText + traitName]
	[h, if(i < traitCount - 1): traitText = traitText + " | "]
}]
[h, if(traitText != ""): setProperty("type", traitText, tokenID)]

[h: sensesText = ""]
[h: senseMarkdown = ""]
[h, if(json.contains(creatureData, "sense_markdown")): senseMarkdown = json.get(creatureData, "sense_markdown")]
[h: senseRemainder = senseMarkdown]
[h: senseStart = indexOf(senseRemainder, "[")]
[h, while(senseStart >= 0), code: {
	[h: senseEnd = indexOf(senseRemainder, "]")]
	[h, if(senseEnd > senseStart), code: {
		[h: senseName = substring(senseRemainder, senseStart + 1, senseEnd)]
		[h, if(sensesText == ""): sensesText = "| "]
		[h, if(sensesText != "| "): sensesText = sensesText + " | "]
		[h: sensesText = sensesText + senseName]
		[h: senseRemainder = substring(senseRemainder, senseEnd + 1)]
	}]
	[h, if(senseEnd <= senseStart): senseRemainder = ""]
	[h: senseStart = indexOf(senseRemainder, "[")]
}]
[h, if(sensesText != ""): setProperty("Percept", sensesText, tokenID)]

[h: setProperty("AON_JSON", aonJson, tokenID)]
[h: setProperty("AON_SourceID", creatureID, tokenID)]
[h: setProperty("AON_ID", aonCreatureNumber, tokenID)]
[h: setProperty("AON_Type", "Creature", tokenID)]
[h: setProperty("AON_Source", "AoN", tokenID)]
[h: setProperty("AON_ImportDate", importDate, tokenID)]
[h: setProperty("AON_ImporterVersion", importerVersion, tokenID)]
[h: setProperty("AON_ManualReviewNeeded", manualReviewNeeded, tokenID)]
[h, if(aonURL != ""): setProperty("AON_URL", aonURL, tokenID)]
[h, if(aonImageURL != ""): setProperty("AON_IMG_URL", aonImageURL, tokenID)]
[h: setProperty("AON_JSON_RAW", creatureData, tokenID)]
